# Creat by Rodrigo Melgar Rodrigues
# Date 26 may 2017 
version: '3'
services:
  docker-jenkins-tools: # JENKINS LATEST
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 2000:8080
      - 50000:50000 
    volumes:
      - "$PWD/jenkins-master:/var/jenkins_home"
#      - /usr/bin/zip:/usr/bin/zip
#      - /usr/bin/unzip:/usr/bin/unzip
#      - /usr/bin/mvn:/usr/bin/mvn
    environment:
      TZ: America/Sao_Paulo

  postgresql: # BANCO DE DADOS POSTGRESQL
    image: orchardup/postgresql:latest
    environment:
      - POSTGRESQL_USER=sonar
      - POSTGRESQL_PASS=xaexohquaetiesoo
      - POSTGRESQL_DB=sonar
    volumes:
      - "$PWD/postgresql:/var/lib/postgresql"

  sonarqube: # SONARQUBE
    image: sonarqube:6.7
    restart: always  
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=xaexohquaetiesoo
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
    volumes:
      - "$PWD/sonarqube/sonarqube-conf:/opt/sonarqube/conf"
      - "$PWD/sonarqube/sonarqube-data:/opt/sonarqube/data"
      - "$PWD/sonarqube/sonarqube-extensions:/opt/sonarqube/extensions"
    ports:
      - "3000:9000"
