version: '3'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.1
    user: root
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - ./etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
